---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../production/cdash/certificates.yaml
  - ../../production/cdash/ingress.yaml
  - ../../production/cdash/namespace.yaml

patches:
  - target:
      kind: Certificate
      name: tls-cdash
      namespace: cdash
    patch: |-
      - op: replace
        path: /spec/commonName
        value: cdash.staging.spack.io
      - op: replace
        path: /spec/dnsNames/0
        value: cdash.staging.spack.io

  - target:
      kind: Ingress
      name: cdash
      namespace: cdash
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: cdash.staging.spack.io
