---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kitware
  namespace: cdash
spec:
  interval: 10m
  url: https://kitware.github.io/helm

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cdash
  namespace: cdash
spec:
  interval: 10m
  chart:
    spec:
      chart: cdash
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: kitware
  values:
    nodeSelector:
      spack.io/node-pool: base

    cdash:
      host: cdash.staging.spack.io
      serviceAccountName: cdash
      website:
        resources:
          requests:
            memory: 50Mi
      worker:
        replicas: 1
        resources:
          requests:
            memory: 50Mi

    postgresql:
      enabled: false

    minio:
      enabled: false
